version: '3.3'

services:
  neo4j:
    image: neo4j:enterprise
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/n3v3r3nd1ng5t0ry
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc"]