CREATE (n:ValueTypesNode)
SET n = {
  nullValue: null,
  boolean: true,
  boolList: [true, false],
  int: 1,
  intList: [ 1, 2, 3],
  float: 1.001,
  floatList: [ 1.001, 1.002 ],
  string: "foo",
  stringList: [ "foo" ],
  point: point({ latitude: 12, longitude: 56 }),
  pointList: [ point({ latitude: 12, longitude: 56 }) ],
  timestamp: timestamp(),
  timestampList: [ timestamp() ],
  date: date(),
  dateList: [ date() ],
  time: time(),
  timeList: [ time() ],
  localTime: localtime(),
  localTimeList: [ localtime() ],
  dateTime: datetime(),
  dateTimeList: [ datetime() ],
  localDateTime: localdatetime(),
  localDateTimeList: [ localdatetime() ],
  duration: duration('P14DT16H12M'),
  durationList: [ duration('P14DT16H12M') ]
}